# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.6.0
        hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
        -   id: check-added-large-files
    -   repo: https://github.com/psf/black
        rev: 24.8.0
        hooks:
        -   id: black
    - repo: local
      hooks:
          - id: generate-pip-requirements
            name: generate-pip-requirements
            entry: hooks/piiip.sh
            language: script
            types: [ python ]
            pass_filenames: false
exclude: env
fail_fast: true
