# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.6.0
        hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
        -   id: check-added-large-files
    -   repo: https://github.com/psf/black
        rev: 24.8.0
        hooks:
        -   id: black
    - repo: local
      hooks:
          - id: generate-pip-requirements
            name: generate-pip-requirements
            entry: bash -c 'pipenv requirements > requirements.txt && exit 0'
            language: system
            types: [ python ]
            always_run: true
            verbose: true
exclude: env
fail_fast: true
